services:
  - type: web
    name: eurusd-signal-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FCS_API_KEY
        value: 0dQWAmgD9T5LtARPKJP0V
      - key: CALENDARIFIC_API_KEY
        value: aDIXAFT1xSZqfeGXkQgc6Z2npRrgdrXd